Models/ConfiguracionUsuarioParticipante.cs
using System.ComponentModel.DataAnnotations;

namespace SGC.Models
{
    public class ConfiguracionUsuarioParticipante
    {
        [Key]
        public int idConfiguracionUsuarioParticipante { get; set; }

        [Display(Name = "Contraseña")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{6,}$", ErrorMessage = "Las contraseñas deben tener al menos un carácter que no sea una letra ni un dígito. Las contraseñas deben tener al menos un dígito ('0'-'9'). Las contraseñas deben tener al menos una letra en mayúscula ('A'-'Z').")]
        public string contrasenia { get; set; }

        public virtual AspNetRoles rol { get; set; }
    }
}

Controllers/ConfiguracionUsuarioParticipanteController.cs
using SGC.CustomAuthorize;
using SGC.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace SGC.Controllers
{
    [Authorize]
    public class ConfiguracionUsuarioParticipanteController : Controller
    {
        private InsecapContext db = new InsecapContext();

        // GET: ConfiguracionUsuarioParticipante
        [CustomAuthorize(new string[] { "/ConfiguracionUsuarioParticipante/" })]
        public ActionResult Index()
        {
            ViewBag.roles = GetRoles();
            return View(db.ConfiguracionUsuarioParticipante.FirstOrDefault());
        }

        // POST: ConfiguracionUsuarioParticipante/
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [CustomAuthorize(new string[] { "/ConfiguracionUsuarioParticipante/" })]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "idConfiguracionUsuarioParticipante,contrasenia")] ConfiguracionUsuarioParticipante configuracion)
        {
            if (Request["rol.Id"] == "" | Request["rol.Id"] == null)
            {
                ModelState.AddModelError("rol.Id", "El campo Rol es obligatorio");
            }
            if (ModelState.IsValid)
            {
                var configuracionBD = db.ConfiguracionUsuarioParticipante.FirstOrDefault();
                var rol = db.AspNetRoles.Find(Request["rol.Id"]);
                if (configuracionBD != null)
                {
                    configuracionBD.contrasenia = configuracion.contrasenia;
                    configuracionBD.rol = rol;
                    db.Entry(configuracionBD).State = EntityState.Modified;
                }
                else
                {
                    configuracion.rol = rol;
                    db.ConfiguracionUsuarioParticipante.Add(configuracion);
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.roles = GetRoles();
            return View(configuracion);
        }

        public SelectList GetRoles()
        {
            return new SelectList(db.AspNetRoles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Id.ToString()
                })
                .ToList(), "Value", "Text");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ConfiguracionUsuarioParticipante/Index.cshtml
@model SGC.Models.ConfiguracionUsuarioParticipante

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page-title">Configuración del Usuario del Participante</h2>

@using (Html.BeginForm("Index", "ConfiguracionUsuarioParticipante", FormMethod.Post, new { }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        Parametros
                    </div>
                </div>
                <div class="portlet-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.contrasenia, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.contrasenia, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.contrasenia, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.rol.Id, "Rol", htmlAttributes: new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.rol.Id, (SelectList)ViewBag.roles, "Seleccionar", htmlAttributes: new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(model => model.rol.Id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Guardar" class="btn btn-primary pull-right" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}